Traceback (most recent call last):
  File "evaluate_agents.py", line 194, in <module>
    evaluate_perf(agent, env, seeds, n_episodes_to_evaluate, save_dir)  
  File "evaluate_agents.py", line 65, in evaluate_perf
    mean_acc_rewards = evaluate_agent(agent, env, n_episodes_to_evaluate)
  File "evaluate_agents.py", line 28, in evaluate_agent
    action = agent.act(curr_obs, mode='eval')
  File "/home/ml/users/nanand4/COMP579-Leaderboard-Backend-New/GROUPS/GROUP_009/agent.py", line 197, in act
    action = self.actor(torch.from_numpy(curr_obs).float().to(self.device))[0] + torch.tensor(self.noise.sample()).to(self.device)
  File "/home/ml/users/nanand4/anaconda3/envs/leaderboard_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ml/users/nanand4/COMP579-Leaderboard-Backend-New/GROUPS/GROUP_009/agent.py", line 55, in forward
    mu = self._forward(x)
  File "/home/ml/users/nanand4/COMP579-Leaderboard-Backend-New/GROUPS/GROUP_009/agent.py", line 37, in _forward
    x = self.activation(layer(x))
  File "/home/ml/users/nanand4/anaconda3/envs/leaderboard_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ml/users/nanand4/anaconda3/envs/leaderboard_env/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
