
Traceback (most recent call last):
  File "evaluate_agents.py", line 194, in <module>
    evaluate_perf(agent, env, seeds, n_episodes_to_evaluate, save_dir)  
  File "evaluate_agents.py", line 65, in evaluate_perf
    mean_acc_rewards = evaluate_agent(agent, env, n_episodes_to_evaluate)
  File "evaluate_agents.py", line 28, in evaluate_agent
    action = agent.act(curr_obs, mode='eval')
  File "XXX/COMP579_project1/GROUPS/GROUP_046/agent.py", line 71, in act
    action_values = self.qnetwork_local(**state)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "XXX/COMP579_project1/GROUPS/GROUP_046/agent.py", line 258, in forward
    out = self.ensemble_NN(nn_out)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "XXX/.conda/envs/COMP579_project/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "XXX/COMP579_project1/GROUPS/GROUP_046/agent.py", line 301, in forward
    weight = self.sigma_weight * torch.ger(self.epsilon_output, self.epsilon_input) + self.mu_weight
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
